### ISSUE TITLE
Pass a glob pattern for matching input files

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-actions/cohort-report#42]
It would be useful to pass a glob pattern for matching input files. For example:

```yaml
run: cohortreport:v2.0.2 output/input_*.csv
```

This would make cohort-report consistent with job-runner and could avoid the following:

```yaml
run: cohortreport:v2.0.2 output/input_2021-01-01.csv output/input_2021-02-01.csv
# snip snip snip
outputs:
  moderately_sensitive:
    output/cohort_report_outputs/descriptives_input_*.csv
```
