### ISSUE TITLE
Summarize some, but not all, variables

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-actions/cohort-report#56]
**Problem:** study definitions often have many variables, but researchers do not want to summarize all of them.

**Related:** The `variable_types` property is a mapping of variable names to variable types. It's required for csv and csv.gz input files (see also #55). It is not required for other types of input files, such as feather input files. The names/types information within `variable_types` takes precedence for other types of input files: that is, if a researcher provides a feather input file and `variable_types`, then the types in the former will be cast (transformed) to the types in the latter. However, `variable_types` does not filter the variables: all variables in the input file must be present in `variable_types`, or an error is raised.

**Solution:** allow researchers to summarize some, but not all, variables. Remove the distinction between csv and csv.gz input files and other types of input files. Replace `variable_types` with an optional `variables` property:

* If `variables` is a mapping, then the keys should be the names and the values the types. All input files will be filtered and cast using the provided names/types.
* If `variables` is a list, then the elements should be the names. All input files will be filtered using the provided names. csv and csv.gz files will be cast to the [`StringDtype`](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html). Other types of input files will not be cast.
* If `variables` is omitted, then do not filter the input files.

An example of a mapping:

```yaml
actions:
  # Snip snip
  generate_report:
    run: cohort-report:v?.?.? output/input.csv
    needs: [generate_study_population]
    config:
      variables:
          age: int
          sex: categorical
          bmi: float
          diabetes: binary
    # Snip snip
```

An example of a list:

```yaml
actions:
  # Snip snip
  generate_report:
    run: cohort-report:v?.?.? output/input.feather
    needs: [generate_study_population]
    config:
      variables:
          age
          sex
          bmi
          diabetes
    # Snip snip
```

See also:

* #55 
* #48 
* #44 
* #34 
* #23
