### ISSUE TITLE
Fix the extract from _project.yaml_

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-actions/cohort-report#68]
The extract from _project.yaml_ does not include the charts in `outputs/moderately_sensitive`. It should, otherwise the report will not include the charts.

[`test-reusable-actions`](https://github.com/opensafely-actions/test-reusable-actions/) has a better example:

```yaml
# ...
  test_cohort_report:
    run: cohort-report:v2.1.0 output/input.csv
    needs: [generate_study_population]
    config:
      output_path: output
      variable_types:
        sex: categorical
        age: int
        age_band: categorical
        has_copd: binary
    outputs:
      moderately_sensitive:
        cohort_report: output/descriptives_input.html
        cohort_report_charts: output/*.png
```
